"""Build a compact radar-comparison data file for LEMON, MINE-like, and Triple-F1."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from statistics import mean
from typing import Any

VARIANTS = ["node_deletion", "edge_deletion", "argument_swap", "polarity_flip", "relation_blur"]


def _load(path: str | None) -> dict[str, Any] | None:
    if not path:
        return None
    return json.loads(Path(path).read_text(encoding="utf8"))


def _variant_scores_from_summary(report: dict[str, Any], metric: str) -> dict[str, float]:
    values: dict[str, list[float]] = {variant: [] for variant in VARIANTS}
    for row in report.get("summary", []) or []:
        variant = row.get("variant")
        if variant in values:
            metrics = row.get("metrics", {})
            if metric in metrics:
                values[variant].append(float(metrics[metric]))
    return {variant: mean(vals) if vals else 0.0 for variant, vals in values.items()}


def _combine_lemon(scoring_paths: list[str]) -> dict[str, float]:
    by_variant: dict[str, list[float]] = {variant: [] for variant in VARIANTS}
    for path in scoring_paths:
        report = _load(path)
        if not report:
            continue
        scores = _variant_scores_from_summary(report, "lemon_full")
        for variant, score in scores.items():
            by_variant[variant].append(score)
    return {variant: mean(vals) if vals else 0.0 for variant, vals in by_variant.items()}


def _variant_scores_from_baseline(report: dict[str, Any], key: str) -> dict[str, float]:
    values: dict[str, list[float]] = {variant: [] for variant in VARIANTS}
    for row in report.get("by_dataset_variant", []) or []:
        variant = row.get("variant")
        if variant in values and key in row:
            values[variant].append(float(row[key]))
    return {variant: mean(vals) if vals else 0.0 for variant, vals in values.items()}


def _axes_from_preservation(scores: dict[str, float], *, recoverability: float, determinism: float) -> dict[str, float]:
    # Sensitivity axes are high when preservation/recoverability is low after a damaging perturbation.
    return {
        "node sensitivity": round(1.0 - scores.get("node_deletion", 0.0), 4),
        "edge sensitivity": round(1.0 - scores.get("edge_deletion", 0.0), 4),
        "direction sensitivity": round(1.0 - scores.get("argument_swap", 0.0), 4),
        "polarity sensitivity": round(1.0 - scores.get("polarity_flip", 0.0), 4),
        "relation sensitivity": round(1.0 - scores.get("relation_blur", 0.0), 4),
        "context recoverability": round(recoverability, 4),
        "determinism": round(determinism, 4),
    }


def build(scoring: list[str], mine: str, triple: str, out: str, tex_out: str | None = None) -> dict[str, Any]:
    lemon_scores = _combine_lemon(scoring)
    mine_report = _load(mine) or {}
    triple_report = _load(triple) or {}
    mine_scores = _variant_scores_from_baseline(mine_report, "mine1_like_score")
    triple_scores = _variant_scores_from_baseline(triple_report, "exact_recovery")

    methods = {
        "LEMON-Factor": _axes_from_preservation(lemon_scores, recoverability=mean(lemon_scores.values()) if lemon_scores else 0.0, determinism=1.0),
        "MINE-1-compatible": _axes_from_preservation(mine_scores, recoverability=float(mine_report.get("mine1_like_score", 0.0)), determinism=0.7 if mine_report.get("mode") == "llm_saved" else 1.0),
        "Triple-F1": _axes_from_preservation(triple_scores, recoverability=float(triple_report.get("exact_recovery", 0.0)), determinism=1.0),
    }
    report = {
        "status": "passed",
        "note": "Radar values are normalized diagnostic properties, not absolute accuracy scores.",
        "axes": list(next(iter(methods.values())).keys()),
        "methods": methods,
        "inputs": {"scoring": scoring, "mine": mine, "triple": triple},
    }
    target = Path(out)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(json.dumps(report, ensure_ascii=False, indent=2), encoding="utf8")
    if tex_out:
        write_tikz(report, tex_out)
    return report


def write_tikz(report: dict[str, Any], tex_out: str) -> None:
    axes = report["axes"]
    methods = report["methods"]
    # Keep the figure lightweight and publication-safe.  Coordinates are computed in TikZ.
    lines = [
        "% Auto-generated by lemon_factor.analysis.metric_radar",
        "\\begin{tikzpicture}[scale=0.78, every node/.style={font=\\scriptsize}]",
        "\\def\\R{2.35}",
        f"\\def\\N{{{len(axes)}}}",
        "\\foreach \\i/\\label in {" + ",".join(f"{i}/{label}" for i, label in enumerate(axes)) + "}{",
        "  \\pgfmathsetmacro\\ang{90-360*\\i/\\N}",
        "  \\draw[gray!35] (0,0) -- (\\ang:\\R);",
        "  \\node[align=center] at (\\ang:\\R+0.38) {\\label};",
        "}",
        "\\foreach \\r in {0.25,0.5,0.75,1.0}{",
        "  \\draw[gray!25] " + " -- ".join(f"(90-360*{i}/\\N:{{\\R*\\r}})" for i in range(len(axes))) + " -- cycle;",
        "}",
    ]
    styles = ["black, thick", "blue!60!black, thick, dashed", "gray!70!black, thick, dotted"]
    for style, (method, values) in zip(styles, methods.items()):
        coords = []
        for i, axis in enumerate(axes):
            val = max(0.0, min(1.0, float(values[axis])))
            coords.append(f"(90-360*{i}/\\N:{{\\R*{val:.4f}}})")
        lines.append(f"\\draw[{style}] " + " -- ".join(coords) + " -- cycle;")
    lines.append("\\begin{scope}[shift={(3.15,1.55)}]")
    for j, (style, method) in enumerate(zip(styles, methods.keys())):
        y = -0.28 * j
        lines.append(f"  \\draw[{style}] (0,{y}) -- (0.35,{y}); \\node[anchor=west] at (0.42,{y}) {{{method}}};")
    lines.append("\\end{scope}")
    lines.append("\\end{tikzpicture}")
    target = Path(tex_out)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text("\n".join(lines) + "\n", encoding="utf8")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--scoring", nargs="+", required=True)
    parser.add_argument("--mine", required=True)
    parser.add_argument("--triple", required=True)
    parser.add_argument("--out", required=True)
    parser.add_argument("--tex-out", default=None)
    args = parser.parse_args()
    report = build(args.scoring, args.mine, args.triple, args.out, tex_out=args.tex_out)
    print(json.dumps(report, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
